[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/instagram/profile"
  to = "/.netlify/functions/instagram-profile"
  status = 200

[[redirects]]
  from = "/api/instagram/image"
  to = "/.netlify/functions/instagram-image"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
